"""remove_prf1

Revision ID: 4f5e2dda35ed
Revises: 88f890b4bff1
Create Date: 2025-12-21 16:36:02.512341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f5e2dda35ed"
down_revision: Union[str, Sequence[str], None] = "88f890b4bff1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eval_results",
        sa.Column("judge_cost_usd", sa.Numeric(precision=20, scale=10), nullable=True),
    )
    op.add_column(
        "eval_results", sa.Column("judge_tokens_total", sa.BigInteger(), nullable=True)
    )
    op.drop_column("eval_results", "recall")
    op.drop_column("eval_results", "precision")
    op.drop_column("eval_results", "f1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eval_results",
        sa.Column(
            "f1", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "eval_results",
        sa.Column(
            "precision",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "eval_results",
        sa.Column(
            "recall",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("eval_results", "judge_tokens_total")
    op.drop_column("eval_results", "judge_cost_usd")
    # ### end Alembic commands ###
