"""add rug_runs and rug_runs_hits

Revision ID: a193b79aafee
Revises: 768af2c16dd2
Create Date: 2025-12-16 22:24:14.535191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a193b79aafee'
down_revision: Union[str, Sequence[str], None] = '768af2c16dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('retriever_top_k', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('distance_metric', sa.String(length=16), nullable=False),
    sa.Column('context_text', sa.Text(), nullable=False),
    sa.Column('final_prompt_text', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('extra_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('usage_prompt_tokens', sa.BigInteger(), nullable=True),
    sa.Column('usage_completion_tokens', sa.BigInteger(), nullable=True),
    sa.Column('usage_total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('latency_ms_total', sa.BigInteger(), nullable=True),
    sa.Column('latency_ms_retrieval', sa.BigInteger(), nullable=True),
    sa.Column('latency_ms_llm', sa.BigInteger(), nullable=True),
    sa.Column('latency_ms_embedding', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_run_hits',
    sa.Column('rag_run_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('qa_pair_id', sa.BigInteger(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('used_in_context', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['qa_pair_id'], ['qa_pairs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rag_run_id'], ['rag_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rag_run_id', 'rank')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_run_hits')
    op.drop_table('rag_runs')
    # ### end Alembic commands ###
